spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xquerylens_db
    username: querylens_user
    password: querylens_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8080
